In [1]:
import pandas as pd
from pathlib import Path

In [2]:
DATA_DIR = Path("data/csvs")

print(DATA_DIR)

data/csvs

In [3]:
employees_df = pd.read_csv(
    DATA_DIR / "employees_with_null.csv"
)

leave_df = pd.read_csv(
    DATA_DIR / "leave_balance.csv"
)

expenses_df = pd.read_csv(
    DATA_DIR / "expense_records.csv"
)

it_assets_df = pd.read_csv(
    DATA_DIR / "IT_assets.csv"
)

offices_df = pd.read_csv(
    DATA_DIR / "office_locations.csv"
)

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [4]:
print("Employees:", employees_df.shape)
print("Leave:", leave_df.shape)
print("Expenses:", expenses_df.shape)
print("IT Assets:", it_assets_df.shape)
print("Offices:", offices_df.shape)

Employees: (100, 8)
Leave: (100, 4)
Expenses: (413, 7)
IT Assets: (134, 7)
Offices: (6, 6)

In [5]:
employees_df.head()

,employee_id,name,department,designation,manager_id,location_id,joining_date,employment_status
0,EMP001,Ananya Sharma,Human Resources,HR Business Partner,NaN,L003,2021-06-15,Active
1,EMP002,Rohan Patel,Engineering,Engineering Lead,NaN,L001,2021-06-15,Active
2,EMP003,Meera Nair,Data Analytics,Senior Data Analyst,NaN,L001,2021-06-15,Active
3,EMP004,Vikas Reddy,Finance,Senior Finance Analyst,NaN,L002,2021-06-15,Active
4,EMP005,Kabir Mehta,Information Technology,IT Manager,NaN,L001,2021-06-15,Active

In [6]:
leave_df.head()

  employee_id  casual_leave  earned_leave  sick_leave
0      EMP001             1            14           8
1      EMP002             5             8          11
2      EMP003             1            13           2
3      EMP004             1            10          12
4      EMP005             9            14           9

In [7]:
expenses_df.head()

,expense_id,employee_id,expense_date,category,description,amount,status
0,EXP0001,EMP010,2026-07-21,Meals,Business trip meals,850,Approved
1,EXP0002,EMP010,2026-07-28,Local Transport,Taxi for client/business meeting,1100,Rejected
2,EXP0003,EMP010,2026-08-04,Mileage,Approved personal vehicle mileage,480,Pending
3,EXP0004,EMP010,2026-08-11,Conference,Approved business conference fee,9000,Approved
4,EXP0005,EMP010,2026-08-18,Hotel,Domestic business hotel accommodation,5000,Rejected

In [8]:
it_assets_df.head()

,asset_id,employee_id,asset_type,asset_name,serial_number,assigned_date,status
0,AST0001,EMP001,Laptop,Dell Latitude 5450,BO-LAP-0001,2021-06-18,Active
1,AST0002,EMP002,Laptop,Dell Latitude 5450,BO-LAP-0002,2021-06-18,Active
2,AST0003,EMP003,Laptop,Dell Latitude 5450,BO-LAP-0003,2021-06-18,Active
3,AST0004,EMP004,Laptop,Dell Latitude 5450,BO-LAP-0004,2021-06-18,Active
4,AST0005,EMP005,Laptop,Dell Latitude 5450,BO-LAP-0005,2021-06-18,Active

In [9]:
offices_df.head()

,location_id,city,office_name,address,facilities,working_hours
0,L001,Bangalore,BlueOrbit Bangalore,"Manyata Tech Park, Nagavara, Bengaluru",Cafeteria; Parking; Gym; Meeting Rooms; Medica...,9:00 AM - 6:00 PM
1,L002,Hyderabad,BlueOrbit Hyderabad,"HITEC City, Madhapur, Hyderabad",Cafeteria; Parking; Meeting Rooms; Recreation ...,9:00 AM - 6:00 PM
2,L003,Chennai,BlueOrbit Chennai,"OMR, Sholinganallur, Chennai",Cafeteria; Parking; Meeting Rooms; Training Room,9:00 AM - 6:00 PM
3,L004,Pune,BlueOrbit Pune,"Hinjewadi IT Park, Pune",Cafeteria; Parking; Gym; Meeting Rooms,9:00 AM - 6:00 PM
4,L005,Mumbai,BlueOrbit Mumbai,"Andheri East, Mumbai",Cafeteria; Meeting Rooms; Parking; Training Room,9:00 AM - 6:00 PM

In [10]:
print("Missing values in employees:")
print(employees_df.isnull().sum())

Missing values in employees:
employee_id          0
name                 0
department           0
designation          0
manager_id           9
location_id          0
joining_date         0
employment_status    0
dtype: int64

In [11]:
print("\nMissing values in leave data:")
print(leave_df.isnull().sum())

Missing values in leave data:
employee_id     0
casual_leave    0
earned_leave    0
sick_leave      0
dtype: int64

In [12]:
print("\nMissing values in IT asset data:")
print(it_assets_df.isnull().sum())

Missing values in IT asset data:
asset_id         0
employee_id      0
asset_type       0
asset_name       0
serial_number    0
assigned_date    0
status           0
dtype: int64

In [13]:
print("\nMissing values in office data:")
print(offices_df.isnull().sum())

Missing values in office data:
location_id      0
city             0
office_name      0
address          0
facilities       0
working_hours    0
dtype: int64

In [14]:
print("Duplicate Employee IDs:",
      employees_df["employee_id"].duplicated().sum())

print("Duplicate Leave Employee IDs:",
      leave_df["employee_id"].duplicated().sum())

print("Duplicate Expense IDs:",
      expenses_df["expense_id"].duplicated().sum())

print("Duplicate Asset IDs:",
      it_assets_df["asset_id"].duplicated().sum())

print("Duplicate Location IDs:",
      offices_df["location_id"].duplicated().sum())

Duplicate Employee IDs: 0
Duplicate Leave Employee IDs: 0
Duplicate Expense IDs: 0
Duplicate Asset IDs: 0
Duplicate Location IDs: 0

In [2]:
import pandas as pd
import glob
import os

# Get all CSV files
csv_files = glob.glob("data/csvs/*.csv")

for file in csv_files:
    
    # Read CSV
    df = pd.read_csv(file)

    print("\n" + "=" * 70)
    print(f"FILE: {os.path.basename(file)}")
    print("=" * 70)

    # Basic information
    print(f"\nShape: {df.shape}")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")

    print("\nColumn Names:")
    print(list(df.columns))

    # Data types
    print("\nData Types:")
    print(df.dtypes)

    # Missing values
    print("\nMissing Values:")
    print(df.isnull().sum())

    # Duplicate rows
    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    # Preview
    print("\nFirst 3 Rows:")
    print(df.head(3))

print("\n" + "=" * 70)
print("DATA VALIDATION COMPLETED")
print("=" * 70)

======================================================================
FILE: office_locations.csv
======================================================================

Shape: (6, 6)
Rows: 6
Columns: 6

Column Names:
['location_id', 'city', 'office_name', 'address', 'facilities', 'working_hours']

Data Types:
location_id      str
city             str
office_name      str
address          str
facilities       str
working_hours    str
dtype: object

Missing Values:
location_id      0
city             0
office_name      0
address          0
facilities       0
working_hours    0
dtype: int64

Duplicate Rows:
0

First 3 Rows:
  location_id       city          office_name  \
0        L001  Bangalore  BlueOrbit Bangalore
1        L002  Hyderabad  BlueOrbit Hyderabad
2        L003    Chennai    BlueOrbit Chennai

                                  address  \
0  Manyata Tech Park, Nagavara, Bengaluru
1         HITEC City, Madhapur, Hyderabad
2            OMR, Sholinganallur, Chennai

                                          facilities      working_hours
0  Cafeteria; Parking; Gym; Meeting Rooms; Medica...  9:00 AM - 6:00 PM
1  Cafeteria; Parking; Meeting Rooms; Recreation ...  9:00 AM - 6:00 PM
2   Cafeteria; Parking; Meeting Rooms; Training Room  9:00 AM - 6:00 PM

======================================================================
FILE: leave_balance.csv
======================================================================

Shape: (100, 4)
Rows: 100
Columns: 4

Column Names:
['employee_id', 'casual_leave', 'earned_leave', 'sick_leave']

Data Types:
employee_id       str
casual_leave    int64
earned_leave    int64
sick_leave      int64
dtype: object

Missing Values:
employee_id     0
casual_leave    0
earned_leave    0
sick_leave      0
dtype: int64

Duplicate Rows:
0

First 3 Rows:
  employee_id  casual_leave  earned_leave  sick_leave
0      EMP001             1            14           8
1      EMP002             5             8          11
2      EMP003             1            13           2

======================================================================
FILE: expense_records.csv
======================================================================

Shape: (413, 7)
Rows: 413
Columns: 7

Column Names:
['expense_id', 'employee_id', 'expense_date', 'category', 'description', 'amount', 'status']

Data Types:
expense_id        str
employee_id       str
expense_date      str
category          str
description       str
amount          int64
status            str
dtype: object

Missing Values:
expense_id      0
employee_id     0
expense_date    0
category        0
description     0
amount          0
status          0
dtype: int64

Duplicate Rows:
0

First 3 Rows:
  expense_id employee_id expense_date         category  \
0    EXP0001      EMP010   2026-07-21            Meals
1    EXP0002      EMP010   2026-07-28  Local Transport
2    EXP0003      EMP010   2026-08-04          Mileage

                         description  amount    status
0                Business trip meals     850  Approved
1   Taxi for client/business meeting    1100  Rejected
2  Approved personal vehicle mileage     480   Pending

======================================================================
FILE: employees_with_null.csv
======================================================================

Shape: (100, 8)
Rows: 100
Columns: 8

Column Names:
['employee_id', 'name', 'department', 'designation', 'manager_id', 'location_id', 'joining_date', 'employment_status']

Data Types:
employee_id          str
name                 str
department           str
designation          str
manager_id           str
location_id          str
joining_date         str
employment_status    str
dtype: object

Missing Values:
employee_id          0
name                 0
department           0
designation          0
manager_id           9
location_id          0
joining_date         0
employment_status    0
dtype: int64

Duplicate Rows:
0

First 3 Rows:
  employee_id           name       department          designation manager_id  \
0      EMP001  Ananya Sharma  Human Resources  HR Business Partner        NaN
1      EMP002    Rohan Patel      Engineering     Engineering Lead        NaN
2      EMP003     Meera Nair   Data Analytics  Senior Data Analyst        NaN

  location_id joining_date employment_status
0        L003   2021-06-15            Active
1        L001   2021-06-15            Active
2        L001   2021-06-15            Active

======================================================================
FILE: IT_assets.csv
======================================================================

Shape: (134, 7)
Rows: 134
Columns: 7

Column Names:
['asset_id', 'employee_id', 'asset_type', 'asset_name', 'serial_number', 'assigned_date', 'status']

Data Types:
asset_id         str
employee_id      str
asset_type       str
asset_name       str
serial_number    str
assigned_date    str
status           str
dtype: object

Missing Values:
asset_id         0
employee_id      0
asset_type       0
asset_name       0
serial_number    0
assigned_date    0
status           0
dtype: int64

Duplicate Rows:
0

First 3 Rows:
  asset_id employee_id asset_type          asset_name serial_number  \
0  AST0001      EMP001     Laptop  Dell Latitude 5450   BO-LAP-0001
1  AST0002      EMP002     Laptop  Dell Latitude 5450   BO-LAP-0002
2  AST0003      EMP003     Laptop  Dell Latitude 5450   BO-LAP-0003

  assigned_date  status
0    2021-06-18  Active
1    2021-06-18  Active
2    2021-06-18  Active

======================================================================
DATA VALIDATION COMPLETED
======================================================================